services:
  web:
    build: .
    ports:
      - "9999:4444"
    volumes:
      - sqlite_data:/app/db
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=localhost,127.0.0.1,u4084wwksc8og0woo844s80w.136.243.151.98.sslip.io

volumes:
  sqlite_data:
