services:
  web:
    build: .
    ports:
      - "9999:4444"
    volumes:
      - sqlite_data:/app/db
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=localhost,127.0.0.1

volumes:
  sqlite_data:
